---
output: github_document
---

```{r}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Relational data with dm

Packages.

```{r}
library(dm, warn.conflicts = FALSE)
library(dplyr, warn.conflicts = FALSE)
```

Data.

```{r}
companies <- tribble(
  # styler: off
  ~companies_id,                                 ~information,
              1,    "alpha sells solar panels and wind mills",
              2, "beta sells steel and installs solar panels",
  # styler: on
)

categories <- tribble(
  # styler: off
  ~companies_id,       ~sector,
              1,      "energy",
              2,  "metallurgy",
              2,      "energy",
              3, "agriculture",
  # styler: on
)
```

A data model (dm) is like a list.

```{r}
database = dm(companies, categories)

database$companies

database$categories
```

For example, using the dm as a list you may examine keys constrains with dplyr.

```{r}
# No primary-key value should be duplicated
database$companies |>
  count(companies_id) |>
  filter(n > 1)

# No primary-key value should be missing
database$companies |>
  filter(is.na(companies_id))

# Each foreign-key value should match a primary key value
# Problem!
categories |>
  anti_join(companies, by = "companies_id")

# Fix
categories |>
  filter(companies_id != 3) |> 
  anti_join(companies, by = "companies_id")
```

But the dm has dedicated features that make it easier to work with it.

```{r}
database

# Add the primary key (pk) and the foreign key (fk)
database2 = database |>
  dm_add_pk(companies, companies_id) |>
  dm_add_fk(categories, companies_id, companies)
database2

# Examine constraints
database2 |>
  dm_examine_constraints()
# Fix
database3 = database2 |>
  dm_filter(categories = (companies_id != 3))
database3 |>
  dm_examine_constraints()

# Other cool things you can do
database3 |>
  dm_flatten_to_tbl(categories, .recursive = TRUE)
```

You may persist the dm by saving it to an R object.

```{r}
path = tempfile(fileext = ".rds")
saveRDS(database3, path)
# And later read it back into R
readRDS(path)
```
