---
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Relational data

The goal of this series is help you understand and work with multiple,
related tables of data.

At the end of this series you will be able to do things like these:

* Understand and use relational data with the dplyr package.
* Define and use relational data models with the dm package.
* Use remote databases.

## Who is the audience?

Anyone who works with two or more related tables of data.

## Why is this important?

> It's rare that a data analysis involves only a single table of
data. Typically you have many tables of data, and you must combine them to
answer the questions that you're interested in. Collectively, multiple
tables of data are called relational data because it is the relations,
not just the individual datasets, that are important.  
-- https://r4ds.had.co.nz/relational-data.html

## Syllabus

### Relational data with dplyr

This meetup covers how to work with relational data with dplyr.

Objectives:

* Understand what is relational data.
* Understand and use the different types of joins.
* Understand what happens when a key has duplicated values.
* Learn how to validate the keys to avoid problems.

### Next (TBC)

* Work with relational data with the dm package.
* Work with a lazy, hosted database. 

## Resources

* YouTube [playlist](https://bit.ly/ds-incubator-videos).
* The
[ds-incubator](https://github.com/2DegreesInvesting/ds-incubator#ds-incubator)
project.
* [Ideas](https://bit.ly/dsi-ideas) for future meetups.
* [Relational data](https://r4ds.had.co.nz/relational-data.html).
* [The dm package](https://cynkra.github.io/dm/).
* [The dbplyr package](https://dbplyr.tidyverse.org/).

## Thanks

Tanks Mirja for motivating me to learn more about relational data.
