---
output: github_document
---

```{r}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Remote databases

Packages.

```{r}
library(dm, warn.conflicts = FALSE)
library(dplyr, warn.conflicts = FALSE)
```

Data.

```{r}
companies <- tribble(
  # styler: off
  ~companies_id,                                 ~information,
              1,    "alpha sells solar panels and wind mills",
              2, "beta sells steel and installs solar panels",
  # styler: on
)

categories <- tribble(
  # styler: off
  ~companies_id,       ~sector,
              1,      "energy",
              2,  "metallurgy",
              2,      "energy",
              3, "agriculture",
  # styler: on
)
```

```{r}
database = dm(companies, categories)

# Or you may save it to a remote database
path = tempfile(fileext = ".sqlite")
connection = DBI::dbConnect(RSQLite::SQLite(), dbname = path)
connection

connection |>
  copy_dm_to(database, temporary = FALSE)

connection |> DBI::dbListTables()
tbl(connection, "companies")
tbl(connection, "categories")
```

